### PR TITLE
Confirm before deletion

### PR DESCRIPTION
**Pull request by cherouvim**

### CODE REVIEW

**Comment by karate** [comment]
Thanks for the PR. The second commit will break the app. 
It's not a redundant statement.
We need to re-assign the `events` variable, to trigger the reactivity and make Svelte re-calculate Events.

> Svelte's reactivity is triggered by assignments. Methods that mutate arrays or objects will not trigger updates by themselves.

So the following line:
https://github.com/karate/mark-time/blob/main/src/lib/Event.svelte#L8
will not trigger any updates, and we have to make a dummy variable assignment instead.

It's the standard way of doing it, it's in the docs:
https://svelte.dev/tutorial/updating-arrays-and-objects

**Comment by cherouvim** [comment]
Wow, talk about magic!

Reverted last commit.

**Comment by cherouvim** [comment]
Note though that the code already re-assigns the `events` variable. And I had tested the code and it seemed to work. I only removed the `events = events;` line.

**Comment by karate** [comment]
Yes, you are correct. The code reassigns at the line above.

**Pull request merged**
